#!/bin/bash

#TFILE=models.tar
TFILE=../Windows7.iso
RESULTS=results-big.txt

for QUEUE_TYPE in l b
do

	for BLOCK_SIZE in 9
	do

		for THREADS in 1 2 4 8 16 24 32 40 48 56 64
		do
			echo "Running test: tpbzip2 $TFILE $BLOCK_SIZE $THREADS $QUEUE_TYPE"
			./tpbzip2 $TFILE $BLOCK_SIZE $THREADS $QUEUE_TYPE | tee -a $RESULTS
			rm -f $TFILE.bz2
		done

	done

done

